### PR TITLE
Add missing pidfile argument to daemon

### PR DESCRIPTION
**Pull request by ledgr**

### CODE REVIEW

**Comment by agentzh** [comment]
@ledgr Will you please explain what problems your change is addressing? Thanks!

**Comment by ton31337** [comment]
looks like it works even without this fix, I see pid file is created

**Comment by agentzh** [comment]
@ton31337 The pid file is created by the nginx process itself.

**Comment by ledgr** [comment]
Yes, after further debugging we found the problem to be in another place.

**Pull request closed without merging**
